logging_level: INFO

results_dir: 'results'
run: '220110-test'

# from ../pypsa-eur-sec/results/220107-google/prenetworks-brownfield
network_file: 'data/elec_s_45_lv1.0__73H-T-H-B-I-solar+p3-offwind+p0.67-dist1-linemaxext10_2020.nc'


#parameters for stripping sector-coupled network
basenodes_to_keep: ["GB4 0","IE4 0"]
node_suffixes_to_keep: ["H2","battery","low voltage","home battery"]
carrier_to_keep: ["offwind","offwind-ac","offwind-dc","solar","solar rooftop","onwind","ror", #generators
                  "PHS","hydro", #storage units
                  "AC", #lines
                  "DC", #links
                  "gas","OCGT","CCGT","oil","coal","H2 Electrolysis","H2 Fuel Cell","H2 pipeline",
                  "home battery charger","home battery discharger","battery charger","battery discharger",
                  "electricity distribution grid",
                  "H2 Store","co2","co2 stored","battery","home battery", #Stores
                  "electricity","industry electricity"]  #Loads
additional_nodes: ["EU oil","EU gas","EU coal","co2 atmosphere","co2 stored"]

#global policy
global:
  policy_type: "co2 cap"
  co2_baseline: 1.2e+7  #MtCO2/a - rough "energy industries" emissions in 1990 and 2020 in IE: 1.2e7
  co2_share: 0.5 #pu  - rough target for 2030
  co2_price: 150 #EUR/tCO2

#data center
ci:
  name: "google"
  node: "IE4 0"
  load: 1000.
  clean_techs: ["clean", "onwind"]
  res_techs: ["onwind"]



scenario:
  policy: ["cfe80","cfe90","cfe95","cfe100","res100"]

solving:
  #tmpdir: "path/to/tmp"
  options:
    formulation: kirchhoff
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    Seed: 123
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
